
all:

# omega1
	make -C omega1/
# omega2
	make -C omega2/
# omega3
# data

clean-all:

# omega1
	-rm -f omega1/libs/libdisp/obj/*.o
	-rm -f omega1/libs/libgr/obj/*.o
	-rm -f omega1/libs/libgr3d/obj/*.o
	-rm -f omega1/libs/libgws/obj/*.o
	-rm -f omega1/libs/rtl/obj/*.o
	
# omega2
	-rm -f omega2/apps/bin/*.BIN
	-rm -f omega2/commands/bin/*.BIN
	-rm -f omega2/drivers/bin/*.BIN
	-rm -f omega2/servers/bin/*.BIN

# omega3
#data



