# Compiling some commands to run on Linux.

all:
	gcc ../../zz/omega2/commands/cat/main.c -o cat
	gcc ../../zz/omega2/commands/c4/c4.c -o c4
	gcc ../../zz/omega2/commands/cmp/main.c -o cmp
	gcc ../../zz/omega2/commands/jackpot/main.c -o jackpot
	gcc ../../zz/omega2/commands/showfun/main.c -o showfun
	gcc ../../zz/omega2/commands/unknown/main.c -o unknown
	gcc ../../zz/omega2/commands/sum/main.c -o sum
	
clean:
	-rm cat
	-rm c4
	-rm cmp
	-rm jackpot
	-rm showfun
	-rm unknown
	-rm sum  
	
