# Compiling some commands to run on Linux.

all:
	gcc ../../userland/commands/cat/main.c -o cat
	gcc ../../userland/commands/c4/c4.c -o c4
	gcc ../../userland/commands/cmp/main.c -o cmp
	gcc ../../userland/commands/jackpot/main.c -o jackpot
	gcc ../../userland/commands/showfun/main.c -o showfun
	gcc ../../userland/commands/unknown/main.c -o unknown

clean:
	-rm cat
	-rm c4
	-rm cmp
	-rm jackpot
	-rm showfun
	-rm unknown
	
