
all:
# Libs and assets.
	make -C alpha1/
# Commands
	make -C alpha2/

clean-all:
# alpha1
	-rm -f alpha1/libs/libdisp/obj/*.o
	-rm -f alpha1/libs/libgr/obj/*.o
	-rm -f alpha1/libs/libgr3d/obj/*.o
	-rm -f alpha1/libs/libgws/obj/*.o
	-rm -f alpha1/libs/rtl/obj/*.o
# omega2
	-rm -f alpha2/commands/bin/*.BIN
	

