
# Client-side GUI applications.

all:

# Virtual terminal connected with the child.
	make -C barnterm/
# Virtual terminal with an embedded command line interpreter.
	make -C terminal/

# First client.
	make -C client
	make -C cmdline


clean:
	-rm bin/*.BIN

