
# ring 3 libs.

all:

# Display support (Server-side?)
	make -C libdisp/
# Gramado Network Server (Client-side)
	make -C libgns/
# Graphics support (Server-side?)
	make -C libgr/
# 3D Graphics support (Server-side?)
	make -C libgr3d/
# Gramado Window System
# Client-side library for the Display server.
	make -C libgws/
# I/O ports in ring3.
	make -C libio01/
# libc and more.
	make -C rtl/
	
	

