# Compiling some commands to run on Linux.

all:
	gcc ../alpha2/commands/cat/main.c -o cat
	gcc ../alpha2/commands/c4/c4.c -o c4
	gcc ../alpha2/commands/cmp/main.c -o cmp
	gcc ../alpha2/commands/jackpot/main.c -o jackpot
	gcc ../alpha2/commands/showfun/main.c -o showfun
	gcc ../alpha2/commands/unknown/main.c -o unknown
	gcc ../alpha2/commands/sum/main.c -o sum

clean:
	-rm cat
	-rm c4
	-rm cmp
	-rm jackpot
	-rm showfun
	-rm unknown
	-rm sum  
	
