
all:

	make -C libdisp/

# Graphics support (Server-side?)
	make -C libgr/
# 3D Graphics support (Server-side?)
	make -C libgr3d/

# Gramado Window System
# Client-side library for the Display server.
	make -C libgws/

clean:

	-rm -f libdisp/*.o
	-rm -f libgr/*.o
	-rm -f libgr3d/*.o
	-rm -f libgws/*.o

	-rm -f libdisp/obj/*.o
	-rm -f libgr/obj/*.o
	-rm -f libgr3d/obj/*.o
	-rm -f libgws/obj/*.o










