
# POSIX commands and more.

all:

	make -C barnsh
	make -C c4
	make -C cat
	make -C cmp
	make -C false
	make -C gramc4
	make -C gramcnf
	make -C jackpot
	make -C miniyacc
	make -C n9
	make -C n10
	make -C n11
	make -C reboot
	make -C sh7
	#make -C shell2
	make -C showfun
	make -C shutdown
	make -C sum
	make -C tascii
	make -C tprintf
	make -C true
	make -C uname
	
