
# Client-side GUI applications.

all:

# The virtual terminal
	make -C barnterm/
	make -C terminal/

	make -C browser
	make -C client
	make -C cmdline
	make -C docv
	make -C editor
	make -C gdm
	make -C setup

clean:
	-rm bin/*.BIN

