
all:

# Client-side GUI applications
	make -C browser/
	make -C editor/
	make -C docv/
	make -C taskbar/
	make -C gdm/
	make -C setup/

# Commands
	make -C jackpot/
	make -C c4/
	make -C gramc4/
	make -C gramcnf/
	make -C miniyacc/
	make -C n9/
	make -C n10/
	make -C n11/
	make -C uname/
	make -C tascii/
	make -C tprintf/
	make -C true/
	make -C false/
	make -C cat/
	make -C cmp/
	make -C showfun/
	make -C sum/

clean:
	-rm bin/*.BIN

